version: '3'
services:
  airflow:
    image: apache/airflow:2.5.1
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Airflow to run Docker
    ports:
      - "8080:8080"
    command: standalone
